### PR TITLE
build: set sensible timout

### PR DESCRIPTION
**Pull request by pkoch**
Based on historical data, clamped between 5 and 60.

See https://github.com/Doist/Issues/issues/5259

### CODE REVIEW

**Review by jankratochvilcz — APPROVED** [review]
I'm curious what is this historical data you mention in this definitely not copy-pasted message 😂

**Comment by pkoch** [comment]
See https://github.com/Doist/Issues/issues/5259#issuecomment-1012023375

**Comment by scottlovegrove** [comment]
This also appears to have been merged with a value of 60 when all other integration PRs opened have requested it be dropped to 5 🤔

**Comment by pkoch** [comment]
Again, based on historical data, see the linked comment. Let's change it to something that you folks feel is right! What would that be?

**Pull request merged**
